version: "3.9"
services:
  app:
    container_name: cf_app
    build: .
    restart: always
    networks:
      - my_net
    environment:
      - TOKEN=6060195927:AAET9G5KPe81tcUJL_yBs671RGQCmrteMaw
      - REDIS_HOST=172.18.0.10

networks:
  my_net:
    external: true

